name: ng_click_disabled_bug_example
description: An example of the bug when having a ng-click and ng-disabled directive set on one button / anchor
version: 0.0.1
environment:
  sdk: '>=0.8.10+6 <2.0.0'
dependencies:
  browser: any
  angular: 1.0.0
  web_components: ">=0.3.4 <0.4.0"
dev_dependencies:
transformers:
- angular:
    html_files:
      - web/index.html
      - web/cmp/example/example.html